PREFIX  rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX  dita: <http://purl.org/dita/ns#>

SELECT  ?sourceId ?relationLabel ?targetId
WHERE
  {   { ?source <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> dita:Topic }
    UNION
      { ?source <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> dita:Map }
      { ?target <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> dita:Topic }
    UNION
      { ?target <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> dita:Map }
    ?source dita:title ?sourceId .
    ?target dita:title ?targetId .
    ?relation rdfs:label ?relationLabel .
    ?source ?relation ?relationObject .
    ?relationObject dita:href ?target
  }