PREFIX dita: <http://purl.org/dita/ns#>
PREFIX dcat: <http://www.w3.org/ns/dcat#>	

#I add hash signs so that blocks are not hyperlinks in visualizations (it actually doesn't work)
SELECT (concat('#',str(?source)) as ?sourceUri) ?sourceLabel (concat('#',str(?target)) as ?targetUri) ?targetLabel ?relationLabel
WHERE { 
GRAPH <http://purl.org/dita/ns> {
?relation rdfs:subPropertyOf dita:referenceObject ;
rdfs:label ?relationLabel .
?RelationClass rdfs:subClassOf dita:ReferenceObject .
}
GRAPH ?graph {
#Replace ?uri with the URI of the context
?uri a dcat:Dataset .
?source ?relation ?relationObject  .
?relationObject dita:href ?target ;
a ?RelationClass .

?source dita:title ?sourceLabel .  
?target dita:title ?targetLabel .   
}

}